name: CI
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
  
    services:
      postgres: 
        image: postgres:16.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: forumapi_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
  

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x # use LTS version instead of 22.14.0
    - run: npm ci
    - run: npm run migrate up
    - run: npm test

    env:
      CI: true
      HOST: localhost
      PORT: 4000
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
      PGDATABASE: forumapi_test
      ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
      REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
      ACCESS_TOKEN_AGE: 3600
