name: CI
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
  
    services:
      postgres: 
        image: postgres:16.6
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: supersecretpassword
          POSTGRES_DB: forumapi_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
  
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        
    - name: Install dependencies
      run: npm install
      
    - name: Run migrations and tests
      run: |
        npm run migrate up
        npm run test
      env:
        NODE_ENV: test
        HOST: localhost
        PORT: 4000
        
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: developer
        PGPASSWORD: supersecretpassword
        PGDATABASE: forumapi_test
                
        ACCESS_TOKEN_KEY: secrets
        REFRESH_TOKEN_KEY: secrets2
        ACCESS_TOKEN_AGE: 3600